### ISSUE TITLE
Counter is confusing

### ISSUE THREAD

**Issue by ltGuillaume** [albertvaka/bettercounter#11]
Say I set a counter to weekly. I _think_ the current counter recalculates the amount of the last 168 hours every time you press +1, right?

- I've pressed +1 quite a few times around 168 hours ago
- I open the app, press +1, the counter goes from 59 to 60
- I leave the app open, the screen goes off
- A few minutes later, I turn on the screen, counter still says 60, x minutes ago
- I press +1 and the counter _still_ says 60, but with "just now"

Apparently, one of the previously counted instances is now _more_ than 168 hours away. But it wasn't removed from the count _before_ I pressed +1. This is quite strange, because either upon activity resume the _count_ isn't updated, but the _last time_ of a +1 is (it said "x minutes ago", not "just now")? If so, this could be solved by recounting upon resuming the activity (in the example, 60 would have been changed to 59 when turned on the screen).

**Comment by albertvaka** [comment]
This was fixed in https://github.com/albertvaka/bettercounter/pull/17
