### ISSUE TITLE
translate to russian

### ISSUE THREAD

**Issue by OmlineEditor** [albertvaka/bettercounter#14]
I want to help translate the program into Russian. tell me which files you need to translate for this, and I will do it

**Comment by albertvaka** [comment]
This is the file: https://github.com/albertvaka/bettercounter/blob/main/app/src/main/res/values/strings.xml

**Comment by OmlineEditor** [comment]
I translated and made a pool request

**Comment by OmlineEditor** [comment]
I checked everything is fine, there is a translation
