### ISSUE TITLE
Add option to reset counter to zero

### ISSUE THREAD

**Issue by rancidfrog** [albertvaka/bettercounter#19]
If the counter is recurrent, sometimes having the option to reset counter to zero is beneficial.
As you can start the count again, without the need of adding a new counter, and filling the name, ...

**Comment by wunschadresse** [comment]
Would love to see that and propose it on a long push on the actual number in the middle (with extra question: do you want to reset this counter?)

**Comment by bttrx** [comment]
Different proposal: Just put the "Reset" function between "Delete" and "Cancel - Save".

I agree with the extra question.

**Comment by albertvaka** [comment]
Added in https://github.com/albertvaka/bettercounter/commit/f5a46e8c8528a581dcfa48984dfaaff4afb6b14e which I'm releasing in v2.5.0 😄

**Comment by Dricc123** [comment]
How do I reset a counter to zero please?

**Comment by bttrx** [comment]
> How do I reset a counter to zero please?

1. Tap counter you wish to reset
2. Tap pencil icon
3. Tap DELETE
4. Tap RESET BUT KEEP

**Comment by albertvaka** [comment]
Maybe the button should be renamed to "delete/reset" to make this more discoverable..

**Comment by Dricc123** [comment]
> Maybe the button should be renamed to "delete/reset" to make this more discoverable..

Oh yes that would be perfect

**Comment by bttrx** [comment]
Changed with Albert's commit 687a87d.
