### ISSUE TITLE
Add Widgets

### ISSUE THREAD

**Issue by HappyClem** [albertvaka/bettercounter#2]
Hi !

Is there any plan for **widgets** ? I'd love to be able to just tap + without even having to open the app.

Nice job already !

**Comment by albertvaka** [comment]
Seems like a good idea. I've never written an Android widget, but the UI and storage are split nicely in the code so it should be easy to add. I'll look into when I have some free time and want to write some Kotlin :)

**Comment by albertvaka** [comment]
I just released version 3.0 with support for widgets, please give it a try and let me know how it works. In the end it turned out it wasn't easy to add widgets, so the implementation is a bit hacky :sweat_smile:

**Comment by albertvaka** [comment]
> The time under the counter could be optional ? And/Or have HH:MM option
If the last count is "recent" (ie: less than 12 hours) we show HH:MM already.

> If the counter is deleted, the widget stay in the same state as last use (even moving it around).
This is a limitation of Android, it doesn't seem to be allowed to delete widgets.
