### ISSUE TITLE
Glitch in the frequency

### ISSUE THREAD

**Issue by CeVague** [albertvaka/bettercounter#24]
Hello,

I am writing to report what doesn't seem correct to me. Apparently, the yearly frequency is calculated from the first event up until now, but I don't think it's a good way to calculate it. For example, with the Théâtre/Ciné/Spectacle category, which has two dates: January 26, 2023 at 11:00 pm (1674770411300) and February 9, 2023 at 8:00 pm (1675969225196). In my opinion, it should have a frequency (as of today) of once every 21 days, but it gives me a frequency of once every 8 days.

Since I'm not sure if it's a voluntary choice or not, I prefer to report it so you can judge for yourself.

(in any case, thanks for this application ^^)

![Screenshot_20230211-105114](https://user-images.githubusercontent.com/17339609/218252366-b8c47f47-7710-4b45-b817-8f483f68566e.png)

**Comment by albertvaka** [comment]
I found it weird that if you start a counter in December for something and you count that thing 12 times during December, it would say "once a month". I prefer to count since the first occurrence, even though it might look weird.

**Comment by CeVague** [comment]
While I personally reset all the counters at the beginning of the year.
But then, that's what I expected and it seems logical too, so it's ok. In any case, it's not a bug.

Have a good day and thanks for your work 👍

**Comment by albertvaka** [comment]
If you set the counters to "yearly", they should still show zero after new year even if they are not reseted. I hope that works :)
