### ISSUE TITLE
Github APK Release

### ISSUE THREAD

**Issue by meichthys** [albertvaka/bettercounter#28]
It would be nice if the APK was released on Github so we could install it directly without having to go through Fdroid or the PlayStore. 
Tools like [Obtainium](https://github.com/ImranR98/Obtainium) would also be able to search for it.

**Comment by albertvaka** [comment]
Done! I've published version 3.0 in Github as well as the usual places :)

I don't do releases often, so if I forget about it the next time please ping me again :smile:

**Comment by DarkCrypt** [comment]
No GitHub release for v3.1.0.

**Comment by albertvaka** [comment]
Oops, thanks for the reminder! Should be fixed now :)

**Comment by DarkCrypt** [comment]
App updated, thank you!
