### ISSUE TITLE
Feature request - Export/Import

### ISSUE THREAD

**Issue by Torenga** [albertvaka/bettercounter#3]
This app looks interessting, but a feature I need before using this as a daily app is export and import. Export to analytic software, export and import as a manual backup solution.

Thank you for your consideration.

**Comment by albertvaka** [comment]
Exporting is definitely on the roadmap, so you can analyze data outside the app.

Importing has less value, but it can be also useful. First, though, I need to find a way to add it without polluting the UI too much.

**Comment by albertvaka** [comment]
Implemented exporting in https://github.com/albertvaka/bettercounter/commit/d4689949c97644f0101559b19f9d216e011316a6 (but still not released).

**Comment by albertvaka** [comment]
Importing has been added in https://github.com/albertvaka/bettercounter/commit/f19654ac59911cff4252c60ba273a17efe3aad0c (to be released in version 2.3).
