### ISSUE TITLE
Add label to timeframe 

### ISSUE THREAD

**Issue by BANOnotIT** [albertvaka/bettercounter#36]
I don't really know what "monthly" will do... Will it reset counter or it will store increments but only show increments for the last month?.. I guess you can disambiguate that by adding a label to that option input.

**Comment by albertvaka** [comment]
Your mean from the "edit counter" screen or from the graph?

I guess both could use a label, maybe the same even. What about "Display interval"?

**Comment by BANOnotIT** [comment]
I encountered it on counter creation view

**Comment by albertvaka** [comment]
I've just released v3.2.0 which adds a label :) Thanks for the feedback!
