### ISSUE TITLE
Feature request: display goal

### ISSUE THREAD

**Issue by Dricc123** [albertvaka/bettercounter#37]
Thanks a lot for the app.
Maybe you don't want to divert towards goal setting features, but I'm thinking maybe it's relevant to be able to set an end-count number that would be a goal to achieve. Showing it like 1/7 when the goal is 7 for example. I see from screenshots that Tally for iOS or Done for iOS have it, but I never used those apps, so don't know much about it.

**Comment by albertvaka** [comment]
This has been requested a few times, so it makes sense to implement it. Implementation idea: It could be a new type of "display interval" that is "Until goal" and when selected it asks you to specify a target number. The target would be stored and then the counter would display `X/<goal>`. Once the goal is reached I guess the simplest thing to do would be to disable the "increase" button.

**Comment by Dricc123** [comment]
@albertvaka  I want to make sure I go running 3 times a month. So I would put 3 as a goal. Rather than disabeling the "increase" button when I reach 3, can the counter be reseted automatically at every start of the month?

**Comment by Dricc123** [comment]
I'm aware that I'm requesting a different function for the app here. From a simple tally counter it would become a habit tracker. If it's not where you want to go, I would understand. I also think that displaying a goal count only makes fully sense combined with a daily/weekly/monthly auto-reset, because we set a daily/weekly/monthly goal. However, we would want to keep the history. For example, although I want my counter to return to zero at the start of the month, I want to see the history of my counts of the previous months, just like it is displayed today (I really like how it is displayed).

**Comment by albertvaka** [comment]
I built it mainly as a habit tracker for myself, but I don't set goals so I didn't put that in. More people requested that so I think it makes sense, though. Maybe I could even start setting goals for myself :P I just want to make sure the app stays simple for people who don't want the goals.

**Comment by Dricc123** [comment]
Maybe you can get inspiration from the Loop Habit Tracker app https://github.com/iSoron/uhabits also available on F-Droid but that app does not work as a tally counter and I much prefer the tally counter system for my use case.

**Comment by albertvaka** [comment]
I've added goals 😃 I'll now make a new release, let me know how it looks for you once you get it 😄

**Comment by Dricc123** [comment]
Are there goals in version 3.2 that was added in F-droid on Dec 27th? I can't find where

**Comment by albertvaka** [comment]
It's in version 4.0. It might take a bit to show up.

**Comment by Dricc123** [comment]
Version 4 is there and I love it! Just what I need. It's simple and it works for me.
I like the checkmark icon but it seems to appear once the goal is exceeded instead of just achieved, for example it does not start at 3/3 but at 4/3. Can you check if you can reproduce that please.

**Comment by albertvaka** [comment]
Ooops, you are right... I made one last minute change and I didn't test it 😓 I'll make a new release with the fix soon.

**Comment by Dricc123** [comment]
Still no update available on F-Droid store...

**Comment by bttrx** [comment]
@Dricc123 Must be a local problem on your phone, because I installed the update v4.0.1 two days ago via F-Droid.

**Comment by Dricc123** [comment]
You're right. I didn't notice it had installed. Sorry about that.
