### ISSUE TITLE
Feature request - Colorized counters

### ISSUE THREAD

**Issue by ghost** [albertvaka/bettercounter#4]
I would love to see colorized counters. Just a few basic colors would be enough.

Here is my a ugly mock-up I made with my phone:
![79cf4e19-4981-4854-bd0f-fba781d47d8b](https://user-images.githubusercontent.com/78130441/106090585-38da7780-6133-11eb-8a87-795cb24571a8.png)

**Comment by albertvaka** [comment]
I'm working on this :)

**Comment by albertvaka** [comment]
I released this in version 1.9 🥳 Thanks for your suggestion!
