### ISSUE TITLE
Wrong date separators

### ISSUE THREAD

**Issue by bttrx** [albertvaka/bettercounter#45]
Hi!
Now that we have different app languages, we also need to use proper date separators, e.g., "/" is wrong for German(y).
Separator should be "." instead. I guess, there is some Android function to get the actual separator from the system.
![Screenshot_20240109-191515](https://github.com/albertvaka/bettercounter/assets/15858666/0f915df3-a13e-4120-abad-eafdc36e256f)

**Comment by albertvaka** [comment]
> I guess, there is some Android function to get the actual separator from the system.

Not for just month & year 😓 I found a workaround though 😄
