### ISSUE TITLE
Remove counters

### ISSUE THREAD

**Issue by 2br-2b** [albertvaka/bettercounter#5]
Hello!

Thank you so much for releasing this app! I've been looking for an app like this for a while! I'll be using this for a completely different purpose: to track peoples' scores during board and card games!

The main problem that I have with it is that there's no way to remove counters after I add them. If I use it to track peoples' scores one game, then I have the last game's scores still on the app next game without being able to remove them.

Could there be an option to remove counters when you are done using them?

**Comment by verbalize-gecko-prune** [comment]
You can remove a counter by swiping right.

**Comment by XandrosDarkstorm** [comment]
Swiping to the right brings the editing menu, not removes a counter and this is not user-friendly  enough idea in my opinion. Also, there are no indication of what will happen if such swipe is done (no icons or tutorials). Swipe actions are not universal, so you have to add some visual help, like a gearbox icon, for example. Take a look at Android notifications or SMS application for icon-visual helper example.
If you don't want to bother with icons and visual help, then replace this swipe with long tap, which i tried the first time instinctively. Usually menus regarding a list item is hidden unnder long tap action, while swiping is done to do something simple, like removing an item or sharing it with other app.
This app looks promising, so i will patiently wait for updates and provide a feedback, where appropriate)

**Comment by albertvaka** [comment]
The reason the delete option is in the menu you get after swiping is to keep the UI clear of additional icons (like three dots or gears), specially if it would require one per counter. Long tap was already used to drag and drop, so I put the "contextual options" in the swipe menu (including delete). In any case, I think the app is simplecenough for any person to familiarize with what it does and how in just a few minutes of trying it.

**Comment by 2br-2b** [comment]
First off, thanks for releasing the app!

I tried using the app, but there's no indication that swiping right brings up the options, nor that dragging rearranges the counters. That's why I started the issue. I think it'd be nicer if there was at least an indicator that swiping does something or that dragging lets you rearrange them; that being said, the app and thus the decision is ultimately yours. I'm not quite sure how this would be best implemented, but I really think something like that would add some nice polish to the app.

**Comment by albertvaka** [comment]
I agree the UI is not the most intuitive, but it's easy to use once you know it... Maybe a first-time tutorial would help?

**Comment by 2br-2b** [comment]
Yes - I think a tutorial would be a huge help to first-time users and would solve the problem. That way, the option to delete a counter is presented, so that the user at least knows that it's possible and isn't left like me wondering why such a feature wasn't included :-)

**Comment by albertvaka** [comment]
Added tutorial tooltips in commit https://github.com/albertvaka/bettercounter/commit/83f076e7a9842c8d01fceab7e7303999fdbc9241

Will be there in the next release :D

![image](https://user-images.githubusercontent.com/980842/107095140-8d9f8180-6808-11eb-80b4-d0987488aa77.png)

**Comment by 2br-2b** [comment]
That looks great! Thank you!

Maybe it should say "Swipe right" rather than just swipe to delete.
