### ISSUE TITLE
Wrong averaging in leap year February

### ISSUE THREAD

**Issue by l3u** [albertvaka/bettercounter#50]
Hi!

First of all thanks for this nice app :-)

I think there's an issue with the "average per month" calculation, and it seems like it has something to do with the current leap year:

![Screenshot_Feb_2024](https://github.com/albertvaka/bettercounter/assets/6770781/f1e13dcf-1af1-4e7e-afcd-df9c46797888)

41 divided by 29 is 1.41..., not 1.32…!

The months before, the average was always correct, e.g. Jan 23: 42 times, 31 days → 1.35, Dec 23: 54 times, 31 days → 1.74, Nov 23: 32 / 30 → 1.07 and so on.

Seems like BetterCounter supposes a leap February has 31 days, at least 41 / 1.32 ≈ 31.

Cheers, Tobias

**Comment by l3u** [comment]
Here's the respective exported dataset:
[bettercounter-export.csv](https://github.com/albertvaka/bettercounter/files/14468954/bettercounter-export.csv)

**Comment by albertvaka** [comment]
It turns out it had nothing to do with the leap years, but the calculation was wrong (it would count until today instead of until the end of the month, if the last count was the previous month). Thanks for reporting it! I'll publish a fix now :smile:

**Comment by l3u** [comment]
Well, then, this actually was coincidence ;-) Thanks a lot for the fix in no time!
