### ISSUE TITLE
Feature request: Max count

### ISSUE THREAD

**Issue by gianpaj** [albertvaka/bettercounter#51]
I'm trying to do fewer crypto trades per week, so I thought this app would help me keep track of how many I do.
Displaying the number in red when I go over the maximum number would be useful.

Thanks for doing this app and open sourcing it!

**Comment by albertvaka** [comment]
The "goal" feature is pretty much this, but shows a check instead of using a different colour.

**Comment by gianpaj** [comment]
oh cool. I guess it's the same. thanks 👍
