### ISSUE TITLE
Feature Request: Ability to set/enter goal number using keyboard instead of +/- buttons

### ISSUE THREAD

**Issue by Plut0nio** [albertvaka/bettercounter#52]
There doesn't seem to be a way to manually enter the goal using the keyboard when editing the counter. I have no choice but to repeatedly tap the + button until I reach the desired goal value. For goals in the hundreds, this is incredibly and needlessly tedious. I should be able to tap the goal number in the edit menu, and a keyboard or (even better) numpad should come up and let me enter the number manually.

**Comment by Plut0nio** [comment]
Now that I think about it, the ability to use a keyboard/numpad to edit the current count of a counter would also be a good idea, though I think there should also be an option to disable this feature somewhere in settings if you're afraid of accidentally messing the count up using the keyboard/numpad.

**Comment by albertvaka** [comment]
Indeed this wasn't very usable, I've fixed it in the upcoming release 4.5.0  :)

Editing a counter isn't that easy, because the counter is not just a number but a list of entries (each one with its date), so it's not clear what should happen if you just change the total.

**Comment by kmantel** [comment]
I find this useful too. What I expect from setting the number directly is basically the same thing that would happen if you just manually tapped the +/- buttons to reach that number. I've implemented this in an ugly way good enough for me personally, but at some point I could clean it if it's something you'd be interested in having: https://github.com/albertvaka/bettercounter/compare/main...0a5c52fb671a837359d11d2b161699e100b70041

**Comment by pmmontanari** [comment]
Hello, was gonna open an issue but just found this. Any plans to implement it, for example with what @kmantel proposed?

**Comment by albertvaka** [comment]
@pmmontanari This issue is about entering goals with the keyboard, please create another one.

**Comment by pmmontanari** [comment]
@albertvaka perfect, I just opened issue #112. Sorry, I hadn't read it very well.
