### ISSUE TITLE
Bad color selection on choose time UI

### ISSUE THREAD

**Issue by MikeStirner** [albertvaka/bettercounter#53]
When I have dark mode on, because my phone's in dark mode, and I long press the plus button, and I can choose a date and time. The time says AM and PM, but those are almost exactly the same color, and so it makes it hard to use. Just to be safe, I usually tap AM or PM just to make sure that it's set to the right thing. So there is a workaround, but it'd be nice to fix that and I think it'd be pretty easy.

**Comment by MikeStirner** [comment]
![Screenshot_20240331_171707_BetterCounter](https://github.com/albertvaka/bettercounter/assets/114986084/f31284c8-7f7c-4590-8a38-2570cc72e040)

**Comment by albertvaka** [comment]
Hey! Thanks for reporting this, and thanks for sponsoring :smiley:

I've just fixed it and the new version should be released soon :rocket:

**Comment by MikeStirner** [comment]
Thanks so much!
