### ISSUE TITLE
Backdating is acting strange.

### ISSUE THREAD

**Issue by MikeStirner** [albertvaka/bettercounter#54]
When you press and hold on the plus to backdate, if you do it at 10.15 pm, then The date that it defaults to is tomorrow, and then if you change it back to today, then your back-dated data point is yesterday, instead of today, like I wanted it to be. I am in Utah if timezone matters here.

So it is 10.15 pm on April 8th and I tried a back date for two hours ago at 8.15 pm and then the counter shows the back date going all the way back to April 7th at 8.15 pm instead of April 8th at 8.15 pm.

**Comment by MikeStirner** [comment]
Okay, now it's 12.06 AM, and I tried to back date two or three minutes ago, but it backdated to one day and three minutes ago.

Hopefully this helps you rule out something.

**Comment by albertvaka** [comment]
Strange 🤔 Does the week start Monday or Sunday for you? Maybe that could explain the off-by-one issue. It works correctly for me, but my weeks start in Monday.

**Comment by MikeStirner** [comment]
On the little calendar that pops up that says Select Date on the Top? The week starts with a Sunday.

**Comment by albertvaka** [comment]
I released version 4.6.1 which handles the case of different week start dates. I'm not 100% sure this is what caused the problem, but it's possible. Let me know if that fixes it, otherwise I will investigate more.

**Comment by MikeStirner** [comment]
Thank you. I'll check it after I get the update through F-Droid and report back here.

**Comment by MikeStirner** [comment]
It seems like the same issue is occurring. It's about 8pm Monday, April 15th, and when I long press the plus, it pulls up a date that is the 16th, and it treats that as if it's today. I'll attach a picture so you can see what it defaults to on the date picker. But then if I correct the date to have it be today, the 15th, then it'll go back in time another 24 hours, which it shouldn't do.
![Screenshot_20240415_204322_BetterCounter](https://github.com/albertvaka/bettercounter/assets/114986084/f47b1973-af82-4e8f-a6e3-dec99592491e)

**Comment by MikeStirner** [comment]
I wonder if it has something to do with time zones? Because at this moment it is the 16th in the UTC. I'll test it in about 4 hours and see if it defaults to the 16th still when it really is the 16th here where I live in Utah. That should help us know what's going on a little better.

**Comment by MikeStirner** [comment]
Okay, I tested it at 11:56 pm and I'm getting the same result where it's defaulting to tomorrow's date and treating tomorrow's date as if it's today as in it's selecting April 16th and treating it as if it was April 15th.

My hypothesis is that once it strikes midnight, the date will default to April 16th, and it will be correct. So let's see if I'm right.

Okay, now it's 12.01 AM and the date is now defaulting to the 16th (see pic)
![Screenshot_20240416_000104_BetterCounter](https://github.com/albertvaka/bettercounter/assets/114986084/fdd665e6-2fde-4ff8-b5a0-37636c9caf7f)
 , which is the current day, but then it's doing the counter 24 hours ago instead of one minute ago. So I'm choosing April 16th at 12am, which is one minute ago, and it's saving it as last happened one day and one minute ago. So it's subtracting 24 hours, no matter what.

**Comment by MikeStirner** [comment]
So it seems like the date picker is probably choosing whatever date it currently is in the UTC time zone.

And then no matter what date and time you choose, it will always subtract 24 hours from that when it actually makes the data point.

**Comment by albertvaka** [comment]
Those are likely two separate issues. I think the picker being on the wrong date by default happens to me as well sometimes (as you say, maybe when the UTC day and my local day are not the same, I want to verify that). The off-by-one-day issue never happens to me though :/

**Comment by MikeStirner** [comment]
Yeah, that definitely makes it hard for you to test then if you're not having the issue ever. Maybe you're to the east of the UTC time zone and I'm to the west and that difference is making the problem. 

I guess I could play around with my time zone in my phone and see if that fixes the problem.

I installed this app on two of my other Android devices, and they're all having the same problem.

**Comment by MikeStirner** [comment]
Yeah, changing my time zone to Australia fixed the problem immediately.

**Comment by MikeStirner** [comment]
And just to be clear, that was a temporary fix, because of course I don't want to have an Australian time zone. When I switched back to the Utah time zone, which is called Mountain Time, then the issue came back.

**Comment by albertvaka** [comment]
You have probably nailed it with the east/west of UTC making the problem. I'll look into it. I'm in GTM+2.

**Comment by albertvaka** [comment]
I think I fixed the issue :D I tested with a phone set to Mountain Time and the problem no longer shows up. I'm publishing a new version now.

**Comment by albertvaka** [comment]
Thanks a lot for your help identifying the problem 🙇

**Comment by MikeStirner** [comment]
Wow, that's a weird problem haha. Glad we could figure it out, and thanks for fixing it so fast!

**Comment by rensaler45** [comment]
Just to let you know that other time zones are affected ... I am in the New York time zone, and the same issue began happening with me, around the same time ... one or two weeks ago.

**Comment by albertvaka** [comment]
Yup, it would happen to everyone, more likely the further you are from GMT 😅 In any case, the last version should have it fixed, please let me know if it doesn't.

**Comment by MikeStirner** [comment]
Fixed for me! Thank you!
