### ISSUE TITLE
Show number of items for the period

### ISSUE THREAD

**Issue by gevhaz** [albertvaka/bettercounter#6]
I love the app, thanks for writing it.

I haven't used it for long but I expect that I will sometimes forget to count an instance of something, and it would be hard to tell from the number presented whether I actually did forget.

When I set a daily counter, I think it would be good if I could see how many times I've counted up on that day. It's easier to think back on how many times I've done something that recently.

Likewise, for weekly counters, you'd show how many times I've counted up for that week.

It could be shown with smaller text under the total number.

**Comment by albertvaka** [comment]
The purposes of the "last updated" timestamp is precisely so you can check
if you forget to count something or if your already did. For me, it has
always been enough. Is the timestamp not enough for your use case?

**Comment by gevhaz** [comment]
It does help, but I think a number would be much clearer. It seems easier to remember how many times I did something today, rather than how many times it has happened after a specific time. 

A specific scenario could be that it has happened 09:00, 11:00, 11:05, 11:10 and 15:00. At around 15:00 it would be hard to remember how many of the middle occurrences I've actually counted.

**Comment by albertvaka** [comment]
Got it. All the things I count happen once a day, so the timestamp is
enough for me to see if I did or didn't count something today. It should be
easy to add this feature, at least for daily counters where I see it more
useful :)

>

**Comment by gevhaz** [comment]
Also, to clarify, I imagine the daily number to be for that weekday, rather than the last 24 hours. Or to reset at 4 AM, when the user is sure to have finished the day but the next day has not yet started. It's easier to think back on what one has done since one woke up.

**Comment by albertvaka** [comment]
I think this can be closed now, given you can use the graph and switch between different display intervals to check when you counted something. Also if the counter is weekly it will only show the entries of the week, so I guess that's pretty much the original request.
