### ISSUE TITLE
A few feature requests to prevent misclicks and others

### ISSUE THREAD

**Issue by ghost** [albertvaka/bettercounter#7]
Thanks for a simple and nice looking counter app! I've used it for a good while now, and i have a few suggestions that in my opinion wouldn't clutter the app and go against your principle of keeping it clean and easy:

1. Delete confirmation. I accidentally pressed delete on a counter that i had running for a long time. Since there is no import function, i didn't get the data back. Would it be possible to add a prompt to confirm track deletion? At that point it has to be intentional, since deleting a counter would require three interactions instead of one swipe and one accidental tap.
2. Long press to undo an entry. You can probably guess i'm a potato thumb with phones, but i find it too easy to also remove the last tick on a counter by accident while scrolling. Loop Habit Tracker and Tickmate, two somewhat similar apps, both implement a long-press to remove an entry.
3. Is it possible to be able to add a short description to a counter, that would show up only when you "open" a counter by tapping on it, above the weekly/monthly/whatever statistics? I sometimes track a few similar items which would benefit from this. Just one row would do it, and be optional obviously. No input = no interface change.
4. Someone else already requested this but an import function would be great. Also, please keep allowing backup apps like Seedvault to backup the app. Some devs enable the flag to prohibit this for some reason.
5. Finally a completely visual thing; a few more colors. There's a little bit too much contrast between for example the brightest green and the rest, i think the aesthetics would benefit from a more "gradient" approach to colors.

**Comment by albertvaka** [comment]
Deleting entries now asks for confirmation.
