### ISSUE TITLE
windows q

### ISSUE THREAD

**Issue by furllmm** [albertvaka/bettercounter#73]
how to build for windows
i rly liked this app
i want build for my windows

**Comment by furllmm** [comment]
@albertvaka

**Comment by albertvaka** [comment]
This app is not for windows

**Comment by furllmm** [comment]
@albertvaka  i know but can i comply for windows i mean

you can give me tip to comply on windows

**Comment by albertvaka** [comment]
No, you can't.

**Comment by furllmm** [comment]
@albertvaka ok can you create html version or python version for me and give me?
last say...

**Comment by albertvaka** [comment]
No, I can't remake the app from scratch for you.
