### ISSUE TITLE
Bug: App crashes when deleting the counter

### ISSUE THREAD

**Issue by FreeWillDeveloper** [albertvaka/bettercounter#75]
System Version: MIUI 14.0.4
Android Version: 12
Language: Chinese
The attachment is a screen recording of the app crash.
https://github.com/user-attachments/assets/f4539244-f0e7-4e1d-b0ee-2285ba0d457c

**Comment by FreeWillDeveloper** [comment]
> System Version: MIUI 14.0.4 Android Version: 12 Language: Chinese The attachment is a screen recording of the app crash. https://github.com/user-attachments/assets/f4539244-f0e7-4e1d-b0ee-2285ba0d457c

I compiled the latest version 4.9.3 and the problem is no longer present.

**Comment by albertvaka** [comment]
4.9.3 should be released already, your shouldn't need to build it yourself. Are you using Google Play or F-Droid?

**Comment by FreeWillDeveloper** [comment]
> 4.9.3 should be released already, your shouldn't need to build it yourself. Are you using Google Play or F-Droid?

I use F-Droid, and the latest release version I see on F-Droid and GitHub is 4.9.1.

**Comment by albertvaka** [comment]
F-Droid takes some time to publish updates. Hopefully it will be published soon. 

Closing this issue since it seems to be resolved 😄

**Comment by FreeWillDeveloper** [comment]
> F-Droid takes some time to publish updates. Hopefully it will be published soon.
> 
> Closing this issue since it seems to be resolved 😄
Thank you for your reply. My main issue right now is [link](https://github.com/albertvaka/bettercounter/issues/68). I look forward to your new version.
