### ISSUE TITLE
Misleading averages

### ISSUE THREAD

**Issue by ltGuillaume** [albertvaka/bettercounter#9]
Say it's Sunday, and I started a counter on Thursday. I view the graph for the last 7 days. The average since Thursday is 9.75, but Better Counter states `Avg: 5.57 times/day`, because it always divides by 7, even though counting started only 4 days ago.

Same thing goes for monthly and yearly: they don't keep into account when the count was first started.

I guess this has its use in cases where you have less than 1 count per day, but not so much if you want to have averages of multiple counts per day.

Could you please add an `Avg from start` next to the `Weekly/Monthly/Yearly avg`, **or** always use the average from start until the first count was a week/month/year ago?

**Comment by albertvaka** [comment]
This was changed in https://github.com/albertvaka/bettercounter/pull/17, to be released in the following days.
